title: Antti Juvonen - Machine Learning and Programming
email: akajuvonen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        Personal notes and thoughts about data science, machine learning,
        programming and tech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: akajuvonen
github_username:  akajuvonen

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: /page:num/
